### ISSUE TITLE
Specify how the plots are going to be created

### ISSUE THREAD

**Issue by KHajduk00** [KHajduk00/MoodoWS#3]

**Comment by nataszalapinska** [comment]
Sorry, what do you exactly mean by that?

**Comment by nataszalapinska** [comment]
Types of plots we can create:
1. Price Distribution:
Histogram or box plot (histograms are easy to understand for everyone, but economics freaks like their boxes) showing the distribution of prices for different types of clothing. This will show the price range of each type. That means we can make one for one type as an example and show them a line of code that creates the plot to show how easily they can change the category they want to check. It would be fun if we can have two to show how we can compare them to each other.

2. Market share comp:
Bar chart (if we can make stacked bar it'll look nice as well) illustrating the market share of each type (category) of clothing. This can be based on the number of items available on the website. This will not show how much revenue we get from each category, but will help us see what the company is placing importance on. We can use this one to check the ratio of different sizes on the website as well.  

3.&4.  Last price & current price | Price change frequency
Scatter plot comparing the last price to the current price for a type of clothing. This can help visualize how prices change. If we add another graph next to it (price change frequency) we can observe not only how prices fluctuate but also how often. The second one can be a bar chart or histogram to make it more clear.


If we want to put it on our report clearly (as nicely as possible so it looks like we know what we are talking about) we can explain it as follows:
1.  Price Distribution by Clothing Type:
Plot Type: Box plot or histogram.
Data Used: Price categorized by type of clothing.
Insight: Understand the price range and distribution for each type of clothing, identify outliers, and compare the affordability or premium nature of different categories.
2. Market Share Visualization:
Plot Type: (Stacked) bar.
Data Used: Number of items available of each category.
Insight: Determine which clothing types are stocked the highest. Determine which sizes are stocked the highest.
3. Price Change Analysis:
Plot Type: Scatter plot.
Data Used: Last price/price before discount versus current price, with each point representing an individual item.
Insight: Analyze the extent of price changes, detect any correlation between price changes and types of clothing.
4. Time Series Analysis:
Plot Type: Histogram
Data Used: Price over time for different types of clothing.
Insight: Track price trends, frequency of changes, identify seasonal variations.
